-- Elite procedural galaxy: a faithful port of newkind/planet.c (itself reverse
-- engineered from BBC Elite). Eight galaxies of 256 systems each, generated by
-- twisting a 6-byte seed; names, economy, government, tech level, population,
-- productivity and radius all fall out of the seed deterministically. Pure Lua
-- (no Playdate API) so it can be unit-tested off-device.

Galaxy = {}

-- the canonical Elite galaxy-1 seed (bytes a,b,c,d,e,f = words 5A4A 0248 B753)
local BASE = { 0x4A, 0x5A, 0x48, 0x02, 0x53, 0xB7 }

local digrams = "ABOUSEITILETSTONLONUTHNOALLEXEGEZACEBISOUSESARMAINDIREA?ERATENBERALAVETIEDORQUANTEISRION"

local function clone(s) return { s[1], s[2], s[3], s[4], s[5], s[6] } end

-- waggle_galaxy: advance the seed one step (planet.c:164)
local function twist(s)
    local x = s[1] + s[3]
    local y = s[2] + s[4]
    if x > 0xFF then y = y + 1 end
    x = x & 0xFF; y = y & 0xFF
    s[1] = s[3]; s[2] = s[4]; s[3] = s[5]; s[4] = s[6]
    x = x + s[3]
    y = y + s[4]
    if x > 0xFF then y = y + 1 end
    s[5] = x & 0xFF; s[6] = y & 0xFF
end

local function rol8(b) return ((b << 1) | (b >> 7)) & 0xFF end

-- the seed each galaxy starts from: rotate every byte left (n-1) times
local function base_seed(galaxy_num)
    local s = clone(BASE)
    for _ = 2, galaxy_num do
        for i = 1, 6 do s[i] = rol8(s[i]) end
    end
    return s
end

local function capitalise(name)
    if #name == 0 then return name end
    return name:sub(1, 1):upper() .. name:sub(2):lower()
end

-- name_planet (planet.c:274): 3 or 4 digram pairs from the seed
function Galaxy.name(seed)
    local s = clone(seed)
    local size = (s[1] & 0x40) == 0 and 3 or 4
    local name = ""
    for _ = 1, size do
        local x = s[6] & 0x1F
        if x ~= 0 then
            x = (x + 12) * 2
            name = name .. digrams:sub(x + 1, x + 1)
            local c2 = digrams:sub(x + 2, x + 2)
            if c2 ~= "?" then name = name .. c2 end
        end
        twist(s)
    end
    return capitalise(name)
end

-- generate_planet_data (planet.c:481)
function Galaxy.data(seed)
    local gov = (seed[3] // 8) & 7
    local econ = seed[2] & 7
    if gov < 2 then econ = econ | 2 end
    local tech = (econ ~ 7) + (seed[4] & 3) + (gov // 2) + (gov & 1)
    local pop = tech * 4 + gov + econ + 1
    local prod = ((econ ~ 7) + 3) * (gov + 4) * pop * 8
    local radius = (((seed[6] & 15) + 11) * 256) + seed[4]
    return { gov = gov, econ = econ, tech = tech, pop = pop, prod = prod, radius = radius,
             x = seed[4], y = seed[2] }
end

-- the 256 system seeds of a galaxy (1..8); system i = seed after 4*(i-1) twists
function Galaxy.systems(galaxy_num)
    local s = base_seed(galaxy_num)
    local list = {}
    for i = 1, 256 do
        list[i] = clone(s)
        twist(s); twist(s); twist(s); twist(s)
    end
    return list
end

-- straight-line distance in tenths of a light year (Elite's chart/fuel metric)
function Galaxy.distance(a, b)
    local dx = math.abs(a[4] - b[4])
    local dy = math.abs(a[2] - b[2])
    return math.floor(4 * math.sqrt(dx * dx + dy * dy / 4) + 0.5)
end

-- next galaxy's seed set follows from rotating the whole seed left
function Galaxy.nextGalaxy(n) return (n % 8) + 1 end
